### PR TITLE
Sharing plan issue 106

### LINKED ISSUE #106: Data sharing plan - refactor and model implementation
In their current state, the MC2 data sharing plans are going to become difficult to manage, as resource contributions increase. One solution is to convert the key information in the data sharing plans to a data model, which we can upload to grant-based Synapse projects.

Benefits here are pretty broad! I can see this helping with: 
- data ingress planning and tracking
- folder provisioning
- information accessibility for contributors
- content validation (likely through schematic)

This could also be tied back to the data landscape survey form - we could revamp the DLS to serve as a data sharing plan submission form. Submissions would go to Synapse, where the plan would be logged and trackable (via DFA or otherwise) and folders would be provisioned (see https://github.com/mc2-center/mc2-center-dcc/issues/54 and https://github.com/mc2-center/mc2-center-dcc/issues/55)

### PR DESCRIPTION
**Pull request by Bankso**
Fixes #106 (again)

## Changelog
- Adds Dataset Sharing Plan and attributes
- Adds controlled vocab for new attribute Dataset Level
- Moved some shared vocab terms from module/dataset --> module/shared
- Update build-jsonld to schematic 24.5.1 and address dependency issue with ipython==8.18.1
- Update a few erroneous entries

### CODE REVIEW

**Review by vpchung — APPROVED** [review]
Saving this as a TODO for a separate PR, but:

Since some of the module files have been moved and the template files have been updated from XLSX to CSV, we will also need to update the doc markdowns in order to reflect their new filepaths/filenames.

**Comment by Bankso** [comment]
> Since some of the module files have been moved and the template files have been updated from XLSX to CSV, we will also need to update the doc markdowns in order to reflect their new filepaths/filenames.

Thank you for pointing this out! Since I'm the one breaking things, I will make those updates 😁

**Comment by vpchung** [comment]
@Bankso thank you!! I don't mind doing it either, so if you have other pressing things to do, just lmk!

**Comment by Bankso** [comment]
@aditigopalan could you please take a quick look at the current [DataDSP model](https://github.com/mc2-center/data-models/pull/110/files#diff-444bef38fb97e0933cf8d6534083b3215547041b725ca355eb12521bb21298df) implementation? I just want to make sure things look reasonable before we merge

**Review by aditigopalan — APPROVED** [review]

**Comment by aditigopalan** [comment]
> @aditigopalan could you please take a quick look at the current [DataDSP model](https://github.com/mc2-center/data-models/pull/110/files#diff-444bef38fb97e0933cf8d6534083b3215547041b725ca355eb12521bb21298df) implementation? I just want to make sure things look reasonable before we merge

Looks good to me!

**Pull request merged**
