### PR TITLE
Multispecies fix for 6.0.1

### PR DESCRIPTION
**Pull request by Bankso**
This PR adds "Multispecies" to shared/dataset_species.csv

### CODE REVIEW

**Review by aditigopalan — COMMENTED** [review]
LGTM, wonder why the json build is failing

**Comment by Bankso** [comment]
> wonder why the json build is failing

It looks like the exit error was caused by the workflow not having any changes to commit after the build finished. I think it's because I updated valid values and built the CSV + JSON-LD locally before committing.

**Comment by aditigopalan** [comment]
> t looks like the exit error was caused by the workflow not having any changes to commit after the build finished. I think it's because I updated valid values and built the CSV + JSON-LD locally before committing.

makes sense, any way to reverse that on your end? If not I can make a new branch for the same

**Review by aditigopalan — APPROVED** [review]

**Comment by aditigopalan** [comment]
Thanks for fixing this!

**Pull request merged**
